
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cloudarmor.matsumo.dev
  resources:
  - securitypolicies
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - cloudarmor.matsumo.dev
  resources:
  - securitypolicies/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - node
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudarmor.matsumo.dev
  resources:
  - securitypolicies
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - cloudarmor.matsumo.dev
  resources:
  - securitypolicies/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - node
  verbs:
  - get
  - list
  - watch
