apiVersion: cloudarmor.matsumo.dev/v1beta1
kind: SecurityPolicy
metadata:
  name: securitypolicy-sample
spec:
  # Add fields here
  description: test
  name: test
  defaultAction: "deny(403)"
  rules:
    - action: "allow"
      description: sample2
      priority: 1103
      srcIpRanges:
        - "192.168.0.0/24"
        - "192.168.1.0/24"



